host: 120.78.182.170
server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: user-auth         #路由的ID
          uri: http://${host}:8001          #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**        # 断言，路径相匹配的进行路由
        - id: cgoods_api
          uri: http://${host}:8008
          predicates:
            - Path=/cgoods/**
        - id: seller_api
          uri: http://${host}:8007
          predicates:
            - Path=/seller/**
        - id: admin_consumer_api
          uri: http://${host}:8010
          predicates:
            - Path=/admin/consumer/**
        - id: goods_api
          uri: http://${host}:8003
          predicates:
            - Path=/goods/**
        - id: admin_provider_api
          uri: http://${host}:8006
          predicates:
            - Path=/admin/provider/**


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://${host}:7001/eureka
    healthcheck:
      enabled: true
    instance:
      instance-id: getway9527
      #访问路径可以显示IP地址
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 60


