host: 120.78.182.170
server:
  port: 8001
spring:
  application:
    name: user-provider
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      #url: jdbc:mysql://localhost:3306/rentsystem?useUnicode=true&characterEncoding=utf-8&useSSL=false
      url: jdbc:mysql://${host}:3306/rentsystem?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      #password: admin
      password: 123456
  devtools:
    restart:
      enabled: true
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2045519528@qq.com
    password: smhizwiimftffdab
    port: 587
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
          #defaultZone: http://localhost:7001/eureka
          defaultZone: http://${host}:7001/eureka
    healthcheck:
      enabled: true
    instance:
          instance-id: user-api
          #访问路径可以显示IP地址
          prefer-ip-address: true
          lease-renewal-interval-in-seconds: 30
          lease-expiration-duration-in-seconds: 60

mybatis:
  configuration:
#   开启驼峰命名
    map-underscore-to-camel-case: true
#    mapper包映射
  mapper-locations: classpath:mapper/*.xml





