server:
  port: 80

spring:
  application:
    name: administratorConsumer80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    healthcheck:
      enabled: true
    instance:
      instance-id: administratorConsumer80
      #访问路径可以显示IP地址
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 60
