server:
  port: 8008

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true


spring:
  mail:
    username: 1830069482@qq.com
    password: axxshflhrkgycfie
    host: smtp.qq.com
    properties:
      mail:
        stmp:
          ssl:
            enable: ture
  application:
    name: cGoodsProvider8008
  datasource:
    username: root
    password: 123456
    #    password: 20001017
    url: jdbc:mysql://120.78.182.170:3306/rentsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    #    url: jdbc:mysql://localhost:3306/rentsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://120.78.182.170:7001/eureka/
    healthcheck:
      enabled: true
    instance:
      instance-id: cgoods-provider
      #访问路径可以显示IP地址
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 60
