server:
  port: 8003
spring:
  application:
    name: goods-provider8003
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      url: jdbc:mysql://localhost:3306/rentsystem?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: admin
  devtools:
    restart:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
          defaultZone: http://localhost:7001/eureka
    instance:
          instance-id: goods-privider8003
          #访问路径可以显示IP地址
          prefer-ip-address: true
mybatis:
  configuration:
#   开启驼峰命名
    map-underscore-to-camel-case: true
#    mapper包映射
  mapper-locations: classpath:mapper/*.xml





